# Generated by Django 3.0.3 on 2020-03-03 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200303_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='prioritizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priority',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='core.Todo'),
        ),
    ]
